apiVersion: v1
kind: Service
metadata:
  name: app-institucional-svc
spec:
  type: LoadBalancer # O ClusterIP si usas Ingress
  selector:
    app: app-institucional
  ports:
    - port: 80
      targetPort: 80
